#!/usr/bin/awk -f

{
    i = j = prefix = $0
    sub(/m->Access0.*/, "", prefix)


    sub(/.*m->Access0\(/, "", i)
    sub(/,.*/, "", i)

    sub(/.*m->Access0\(/, "", j)
    sub(/.*,[ ]*/, "", j)
    suffix = j
    sub(/).*/, "", j)
    sub(/.*\)/, "", suffix);

    rec  = sprintf("%sm->Access0(%s, %s)%s", prefix, i, j, suffix);

    if (""rec == ""$0) {
	printf "%sm->d[%s + nm * (%s)]%s\n", prefix, i, j, suffix;
    } else
	print
}
